# Generated by Django 4.2.7 on 2023-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_paciente", models.IntegerField()),
                ("id_medico", models.IntegerField()),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_termino", models.TimeField()),
            ],
        ),
    ]
